/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-18 02:26:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/samuel.almeida/java/FinTechServelts/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinTechServelts/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425989470000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1667756598155L));
    _jspx_dependants.put("jar:file:/C:/Users/samuel.almeida/java/FinTechServelts/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinTechServelts/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425989470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./recources/css/styleDashboard.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./recources/css/styleGlobal.css\">\r\n");
      out.write("\r\n");
      out.write("<title>DashBoard</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header id=\"header\">\r\n");
      out.write("		<img src=\"./recources/image/foto_perfil.png\" alt=\"Foto do perfil\" />\r\n");
      out.write("	</header>\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<nav>\r\n");
      out.write("			<div>\r\n");
      out.write("				<img src=\"./recources/image/home.svg\" alt=\"Icone de casa\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"entrada-receita\" data-toggle=\"modal\"\r\n");
      out.write("				data-target=\"#modal-receita\">\r\n");
      out.write("				<img src=\"./recources/image/entrada_dinheiro.svg\"\r\n");
      out.write("					alt=\"Icone de entrada dinheiro\" />\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"entrada-despesa\" data-toggle=\"modal\"\r\n");
      out.write("				data-target=\"#modal-despesa\">\r\n");
      out.write("				<img src=\"./recources/image/saida_dinheiro.svg\"\r\n");
      out.write("					alt=\"Icone saída de dinheiro\" />\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<div>\r\n");
      out.write("			<section id=\"div-saldo-mes\">\r\n");
      out.write("				<div id=\"div-info\">\r\n");
      out.write("					<span class=\"text-align-center\" id=\"mes\">Abril 2022</span> <span\r\n");
      out.write("						class=\"text-align-center\" id=\"text-saldo-mes\">Saldo do mês</span>\r\n");
      out.write("					<span id=\"saldo-mes\">R$ 1.650,50</span>\r\n");
      out.write("					<div id=\"div-icone-olho\">\r\n");
      out.write("						<img id=\"icone_olho\" src=\"./recources/image/olho.svg\"\r\n");
      out.write("							alt=\"Icone de olho\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"div-despesas-orcamento\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<span>Despesas</span> <span>R$ 700,00</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<span>Orçamento do mês</span> <span>R$ 2.350,00</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"div-progress-bar\">\r\n");
      out.write("					<div style=\"-progress: 25; width: 70%; height: 15px\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("\r\n");
      out.write("			<section id=\"div-despesas-por-categoria\">\r\n");
      out.write("				<span>Despesas por categoria</span>\r\n");
      out.write("				<div>\r\n");
      out.write("					<div id=\"div-grafico\">\r\n");
      out.write("						<img src=\"./recources/image/grafico.svg\" alt=\"Gráfico\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"div-lista-grafico\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li>Alimentação</li>\r\n");
      out.write("							<li>Strimmer</li>\r\n");
      out.write("							<li>Transporte</li>\r\n");
      out.write("							<li>Água e Luz</li>\r\n");
      out.write("							<li>Outros</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("\r\n");
      out.write("			<section id=\"div-transacoes-recentes\">\r\n");
      out.write("				<span>Suas Receitas</span>\r\n");
      out.write("				<div>\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<button type=\"button\" id=\"btn-adicionar-transacao\"\r\n");
      out.write("						data-toggle=\"modal\" data-target=\"#modal-receita\"\r\n");
      out.write("						class=\"btn btn-primary\">Adicionar receita</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("			<div id=\"div-planejamento-do-mes\">\r\n");
      out.write("				<span>Planejamento do mês</span>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"infos-planejamento-do-mes\">\r\n");
      out.write("					<div class=\"imagens-planejamento-do-mes\">\r\n");
      out.write("						<img src=\"./recources/image/carrinho_supermercado.svg\"\r\n");
      out.write("							alt=\"Carrinho de supermercado\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"div-infos-gastos\">\r\n");
      out.write("							<span>Supermercado</span> <span>R$ 550</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"div-progress-bar\">\r\n");
      out.write("							<div id=\"progress-carrinho\" style=\"progress: 45\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"qtd-restou\">\r\n");
      out.write("							<span>Restou R$ 170</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"infos-planejamento-do-mes\">\r\n");
      out.write("					<div class=\"imagens-planejamento-do-mes\" id=\"div-trem\">\r\n");
      out.write("						<img src=\"./recources/image/trem.svg\" alt=\"Icone de um trem\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"div-infos-gastos\">\r\n");
      out.write("							<span>Transporte</span> <span>R$ 250</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"div-progress-bar\">\r\n");
      out.write("							<div id=\"progress-transporte\" style=\"-progress: 30\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"qtd-restou\">\r\n");
      out.write("							<span>Restou R$ 100</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"infos-planejamento-do-mes\">\r\n");
      out.write("					<div class=\"imagens-planejamento-do-mes\" id=\"div-lampada\">\r\n");
      out.write("						<img src=\"./recources/image/lampada.svg\"\r\n");
      out.write("							alt=\"Icone de uma lâmpada\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"div-infos-gastos\">\r\n");
      out.write("							<span>Luz</span> <span>R$ 150</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"div-progress-bar\">\r\n");
      out.write("							<div id=\"progress-luz\" style=\"-progress: 100\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"qtd-restou\">\r\n");
      out.write("							<span>Restou R$ 0</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"infos-planejamento-do-mes\">\r\n");
      out.write("					<div class=\"imagens-planejamento-do-mes\" id=\"div-cinema\">\r\n");
      out.write("						<img src=\"./recources/image/cinema.svg\" alt=\"Icone de cinema\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"div-infos-gastos\">\r\n");
      out.write("							<span>Strimmer</span> <span>R$ 80</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"div-progress-bar\">\r\n");
      out.write("							<div id=\"progress-strimmer\" style=\"-progress: 100\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"qtd-restou\">\r\n");
      out.write("							<span>Restou R$ 100</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"div-definir-novo-orcamento\">\r\n");
      out.write("					<button type=\"button\" id=\"btn-definir-novo-orcamento\"\r\n");
      out.write("						class=\"btn btn-primary\">Definir novo orçamento</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"modal fade\" id=\"modal-receita\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"modal-receita\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"modal-receita\">Adicionar Receita</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<form action=\"dashboard\" method=\"POST\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<input type=\"hidden\" name=\"acao\" value=\"cadastrarReceita\" />\r\n");
      out.write("\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"descricao-receita\" class=\"form-label\">\r\n");
      out.write("								Descrição</label> <input type=\"text\" name=\"descricao\"\r\n");
      out.write("								class=\"form-control\" id=\"descricao-receita\"\r\n");
      out.write("								placeholder=\"Ex. Salário\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"exampleFormControlInput1\" class=\"form-label\">Data</label>\r\n");
      out.write("							<input type=\"date\" name=\"data\" class=\"form-control\"\r\n");
      out.write("								id=\"exampleFormControlInput1\" placeholder=\"name@example.com\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"valor\" class=\"form-label\">Valor</label> <input\r\n");
      out.write("								type=\"text\" name=\"valor\" class=\"form-control\" id=\"valor\"\r\n");
      out.write("								placeholder=\"Ex. 1.200\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"modal-footer\">\r\n");
      out.write("							<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("								data-dismiss=\"modal\">Fechar</button>\r\n");
      out.write("							<input type=\"hidden\" id=\"msgCadastroReceita\"\r\n");
      out.write("								value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ msgCadastroReceita }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input type=\"hidden\"\r\n");
      out.write("								id=\"msgErroCadastroReceita\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ msgErroCadastroReceita }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary\">Salvar</button>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"modal fade\" id=\"modal-editar-receita\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"modal-editar-receita\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"modal-editar-receita\">Editar Receita</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<form action=\"dashboard\" method=\"POST\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<input type=\"hidden\" name=\"acao\" value=\"editarReceita\" /> \r\n");
      out.write("						<input type=\"hidden\" name=\"codigoDeEditarReceita\" id=\"codigoDeEditarReceita\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"descricao-receita\" class=\"form-label\">\r\n");
      out.write("								Descrição</label> <input type=\"text\" name=\"descricao\"\r\n");
      out.write("								class=\"form-control\" id=\"descricao-receita\"\r\n");
      out.write("								placeholder=\"Ex. Salário\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"exampleFormControlInput1\" class=\"form-label\">Data</label>\r\n");
      out.write("							<input type=\"date\" name=\"data\" class=\"form-control\"\r\n");
      out.write("								id=\"exampleFormControlInput1\" placeholder=\"name@example.com\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"valor\" class=\"form-label\">Valor</label> <input\r\n");
      out.write("								type=\"text\" name=\"valor\" class=\"form-control\" id=\"valor\"\r\n");
      out.write("								placeholder=\"Ex. 1.200\" />\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"modal-footer\">\r\n");
      out.write("							<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("								data-dismiss=\"modal\">Fechar</button>\r\n");
      out.write("							<input type=\"hidden\" id=\"msgCadastroReceita\"\r\n");
      out.write("								value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ msgCadastroReceita }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input type=\"hidden\"\r\n");
      out.write("								id=\"msgErroCadastroReceita\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ msgErroCadastroReceita }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary\">Salvar</button>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"modal fade\" id=\"modal-despesa\" tabindex=\"-2\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"modal-despesa\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"modal-despesa\">Adicionar despesa</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"descricao-receita\" class=\"form-label\">Descrição</label>\r\n");
      out.write("						<input type=\"text\" class=\"form-control\" id=\"descricao-receita\"\r\n");
      out.write("							placeholder=\"Ex. Transporte\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"exampleFormControlInput1\" class=\"form-label\">Data</label>\r\n");
      out.write("						<input type=\"date\" class=\"form-control\"\r\n");
      out.write("							id=\"exampleFormControlInput1\" placeholder=\"name@example.com\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"valor\" class=\"form-label\">Valor</label> <input\r\n");
      out.write("							type=\"number\" class=\"form-control\" id=\"valor\" placeholder=\"1.200\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<p>É uma despesa mensal</p>\r\n");
      out.write("					<div class=\"form-check\">\r\n");
      out.write("						<input class=\"form-check-input\" type=\"checkbox\" value=\"\"\r\n");
      out.write("							id=\"flexCheckDefault\" /> <label class=\"form-check-label\"\r\n");
      out.write("							for=\"flexCheckDefault\"> Sim </label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-check\">\r\n");
      out.write("						<input class=\"form-check-input\" type=\"checkbox\" value=\"\"\r\n");
      out.write("							id=\"flexCheckChecked\" checked /> <label class=\"form-check-label\"\r\n");
      out.write("							for=\"flexCheckChecked\"> Não </label>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div id=\"div-select\">\r\n");
      out.write("						<span>Selecione a categoria da despesa</span> <select\r\n");
      out.write("							id=\"select-despesa\" class=\"form-select\"\r\n");
      out.write("							aria-label=\"Default select example\">\r\n");
      out.write("							<option selected>Selecione</option>\r\n");
      out.write("							<option value=\"1\">One</option>\r\n");
      out.write("							<option value=\"2\">Two</option>\r\n");
      out.write("							<option value=\"3\">Three</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"modal-footer\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("							data-dismiss=\"modal\">Fechar</button>\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-primary\">Salvar</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\" src=\"./recources/js/dashboard.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("		integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"\r\n");
      out.write("		integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("		integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /dashboard.jsp(87,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/dashboard.jsp(87,5) '${receitas }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${receitas }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /dashboard.jsp(87,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("receita");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("						<div class=\"transacoes\" id=\"entrada-receita\"\\>\r\n");
            out.write("							<div>\r\n");
            out.write("								<img src=\"./recources/image/entrada_dinheiro.svg\"\r\n");
            out.write("									alt=\"Entrada de dinheiro\" />\r\n");
            out.write("							</div>\r\n");
            out.write("							<div class=\"div-info-transacoes\">\r\n");
            out.write("								<span class=\"descricao_transacoes\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${receita.descricao }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("								");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("							</div>\r\n");
            out.write("							<div>\r\n");
            out.write("								<span class=\"dinheiro-transacao\"> ");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("								</span>\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("							<div>\r\n");
            out.write("								<form action=\"dashboard\" method=\"post\">\r\n");
            out.write("									<input type=\"hidden\" name=\"acao\" value=\"excluirReceita\">\r\n");
            out.write("									<input type=\"hidden\" name=\"codigoReceita\"\r\n");
            out.write("										value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${receita.cdReceita }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("									<button class=\"btn-lixeira\" type=\"submit\">\r\n");
            out.write("										<img class=\"lixeira\" src=\"./recources/image/lixeira.svg\"\r\n");
            out.write("											alt=\"ícone de lixeira\">\r\n");
            out.write("									</button>\r\n");
            out.write("								</form>\r\n");
            out.write("							</div>\r\n");
            out.write("							<div>\r\n");
            out.write("								<button class=\"btn-lixeira\" type=\"submit\" data-toggle=\"modal\"\r\n");
            out.write("									data-target=\"#modal-editar-receita\"\r\n");
            out.write("									onclick=\"codigoDeEditarReceita.value = ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${receita.cdReceita}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\r\n");
            out.write("									<img class=\"editar\" src=\"./recources/image/editar.svg\"\r\n");
            out.write("										alt=\"ícone de editar\">\r\n");
            out.write("								</button>\r\n");
            out.write("\r\n");
            out.write("							</div>\r\n");
            out.write("						</div>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /dashboard.jsp(96,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${receita.data.time }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /dashboard.jsp(96,8) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("dd/MM/yyyy");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /dashboard.jsp(100,42) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setType("currency");
      // /dashboard.jsp(100,42) name = maxFractionDigits type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setMaxFractionDigits(2);
      // /dashboard.jsp(100,42) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${receita.valor}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fmaxFractionDigits_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }
}
